site_name: Audiometer Documentation
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - User Guide:
      - Introduction: user_guide/intro.md
      - Installation: user_guide/installation.md
      - Hardware Requirements: user_guide/hardware.md
  - Reference Manual:
      - audio_player: api/audio_player.md
      - audiogram: api/audiogram.md
      - main: api/main.md
      - model: api/model.md
      - ui: api/ui.md
  - About: about.md
