site_name: Audiometer Documentation
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            separate_signature: true
            show_root_full_path: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - admonition 

nav:
  - Start: index.md
  - Benutzerhandbuch (User Guide):
      - Einleitung (Introduction): user_guide/intro.md
      - Installation: user_guide/installation.md
      - Hardware: user_guide/hardware.md
  - Reference Manual:
      - audio_player: api/audio_player.md
      - audiogram: api/audiogram.md
      - main: api/main.md
      - model: api/model.md
      - ui: api/ui.md
  - Über Audiometer (About): about.md
