site_name: Audiometer Documentation
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - User Guide:
      - Introduction: user_guide/intro.md
      - Installation: user_guide/installation.md
  - API Reference:
      - model: api/model.md
      - ui: api/ui.md
      - main: api/main.md
  - About: about.md
